name: react-ts-template continuous integration
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn --disable-progress
      - run: yarn build --disable-progress
     
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn --disable-progress
      - run: yarn validate
     
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.16'
      - run: npm i -g yarn
      - run: yarn --disable-progress
      - run: yarn test

  # push-image:
  #   runs-on: ubuntu-latest
  #   needs: [build, lint, test]
  #   env:
  #     DOCKER_REPO: react-ts-template
  #     SHA: ${GITHUB_SHA::7}
  #     BRANCH: ${GITHUB_REF}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '10.16'
  #     - run: npm i -g yarn
  #     - run: yarn --disable-progress
  #     - run: yarn build --disable-progress
  #     - run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
  #     - run: docker build -t ${{ env.DOCKER_REPO }}:${{ env.SHA }} -t ${{ env.DOCKER_REPO }}:latest .
  #     - run: docker push ${{ env.DOCKER_REPO }}:${{ env.SHA }}
  #     - run: test `echo ${{ env.BRANCH }} | grep "master"` && docker push ${{ env.DOCKER_REPO }}:latest || echo "Not pushing latest because on branch"
